name: Build & Push to Amazon ECR

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      US_EAST_1_BUNDLE:
        required: false

env:
  IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Write PEM file
        if: github.event.inputs.US_EAST_1_BUNDLE != ''
        run: printf "%b" "${{ secrets.US_EAST_1_BUNDLE }}" > us-east-1-bundle.pem

      - name: Set file permissions for PEM file 
        if: github.event.inputs.US_EAST_1_BUNDLE != ''
        run: chmod 600 us-east-1-bundle.pem

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ github.sha }}  # Apenas a tag SHA
          build-args: |
            COMMIT_HASH=${{ github.sha }}
