name: Build & Push to Amazon ECR

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      US_EAST_1_BUNDLE:  # Adicionando o segredo para o certificado
        required: false

env:
  IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Forçar Node.js 20

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Compatível com Node.js 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Já compatível com Node.js 20
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Write PEM file
        echo "${{ secrets.US_EAST_1_BUNDLE }}" | tr '/n' '\n' > us-east-1-bundle.pem


      - name: Set file permissions for PEM file
        run: chmod 600 us-east-1-bundle.pem

      - name: Verify PEM file
        run: ls -l us-east-1-bundle.pem
      


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2  # Atualizado para a versão 2
        with:
          mask-password: true  # Máscara de senha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Atualizado

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4  # Atualizado
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # Atualizado
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
