name: Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      ECS_CLUSTER:
        required: true
        type: string
      ECS_SERVICE:
        required: true
        type: string
      TASK_NAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

env:
  IMAGE_NAME: ${{ inputs.IMAGE_NAME }}

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar as credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Obter o AWS Account ID dinamicamente
      - name: Get AWS Account ID
        id: get-account-id
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV

      # 3. Atualizar Task Definition do ECS
      - name: Update ECS Task Definition
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLUSTER_NAME: ${{ inputs.ECS_CLUSTER }}
          SERVICE_NAME: ${{ inputs.ECS_SERVICE }}
          TASK_DEFINITION: ${{ inputs.TASK_NAME }}
          IMAGE_URI: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest
        run: |
          # Obter a task definition atual
          TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          # Criar nova task definition com a nova imagem
          NEW_TASK_DEFINITION=$(aws ecs register-task-definition \
            --family $TASK_DEFINITION \
            --container-definitions "[{\"name\":\"${{ inputs.TASK_NAME }}\",\"image\":\"$IMAGE_URI\",\"essential\":true,\"memory\":512,\"cpu\":256,\"portMappings\":[{\"containerPort\":3000,\"hostPort\":3000,\"protocol\":\"tcp\"}]}]" \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          # Atualizar o serviço ECS com a nova task definition
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition $NEW_TASK_DEFINITION
